### ISSUE TITLE
Fields with "auto-disable" flag get disabled on server restart/plugin load

### ISSUE THREAD

**Issue by Taybosquee** [marcelo-mason/PreciousStones#1001]
Fields with "auto-disable" flag are disabled on server restart/plugin load.

Plugin version: v10.3.5
Game version: v1.10.0

Field tested with:

```
- title: '&cTest [v7]'
  required-permission: preciousstones.test
  meta-name: '&bTest Field'
  meta-lore:
  - '&7This is for breaking Phade''s toys'
  single-use: true
  breakable: true
  no-allowing: true
  sneak-to-place: true
  block: 1
  radius: 10
  cuboid: true
  welcome-message: true
  farewell-message: true
  auto-disable: 60d
```
