### ISSUE TITLE
how can i fix this??

### ISSUE THREAD

**Issue by mauerizo-DownyCraft** [marcelo-mason/PreciousStones#1056]
hi, i already install precious stone plugin, but when i make a shop (with signshop) the block that it gives you is a normal block, and i need to put it and take it back to make it work? how can i fix this??

what i need is a plugin to sell protections stones, or how do i make that when someone buy a block from a signshop they just place it on the floor and protect?

**Comment by marcelo-mason** [comment]
Make sure signshop blocks come out with metadata, if the metadata name matches it will work as PS block.

**Comment by marcelo-mason** [comment]
Alternatively you can use the [meta-autoset](http://preciousstones.shoutwiki.com/wiki/Field_Flag_Reference#meta-autoset) flag on the pstone.  But this has other side-effects so its advisable to use only on blocks types that can't be mined from the world.

**Comment by mauerizo-DownyCraft** [comment]
yeah ty, i am using silverfish stones like protections.

So the only thing i need to do is to add meta-autoset on my pstones?

**Comment by mauerizo-DownyCraft** [comment]
oh, and wich is the command to add a flag to a ps block? or i need to add it in the config and how?

TY soo much

**Comment by mauerizo-DownyCraft** [comment]
well here is the thing. i enabled the meta-autoset but when i place the block the first time is not working, if i  brake it down and place it a second time it works. how can i make it to work since the first time? ty

**Comment by marcelo-mason** [comment]
Yeah in the config, each pstone is defined by a collection of flags.  They are all the in the force-fields list.  Just add the flag there on each block.

**Comment by marcelo-mason** [comment]
Here read the first few paragraphs here on how to use flags: https://www.spigotmc.org/resources/preciousstones.5270/

**Comment by marcelo-mason** [comment]
If meta-autoset is enabled then that shouldn't happen.  Try restarting the server.

**Comment by mauerizo-DownyCraft** [comment]
so the problem is, that when i place for first time my ps it doesnt work, but if i brake it and place it down a second time, it works. i want to know how to make it work at the first time

i alredy put on the meta-autoset to true, here is my config

```
unbreakable-blocks: []
force-field-blocks:
- title: Cubo de cobblestone
  block: '97:1'
  radius: 4
  custom-height: 4
  meta-name: '&bCubo de cobblestone 4x4x4'
  meta-autoset: true
  meta-lore:
  - '&eprotege un area de 4x4x4'
  prevent-fire: true
  prevent-place: true
  prevent-destroy: true
  prevent-vehicle-destroy: true
  prevent-enderman-destroy: true
  prevent-explosions: true
  prevent-unprotectable: true
  prevent-item-frame-take: true
  protect-armor-stands: true
  prevent-flow: true
  protect-crops: true
  protect-inventories: true
  ?welcome-message: false
  ?farewell-message: false
  ?prevent-portal-enter: false
  ?prevent-portal-destination: false
  ?prevent-portal-create: false
  ?prevent-vehicle-enter: false
  ?prevent-vehicle-exit: false
  ?prevent-teleport: false
  command-blacklisting: false
  can-change-owner: true
  enable-on-src: true
  mixing-group: 1
  rentable: false
  buyable: false
  cuboid: false
- title: Cubo de piedra
  block: 97
  radius: 6
  custom-height: 6
  meta-name: '&bCubo de piedra 6x6x6'
  meta-autoset: true
  meta-lore:
  - '&eprotege un area de 6x6x6'
  prevent-fire: true
  prevent-place: true
  prevent-destroy: true
  prevent-vehicle-destroy: true
  prevent-enderman-destroy: true
  prevent-explosions: true
  prevent-unprotectable: true
  prevent-item-frame-take: true
  protect-armor-stands: true
  prevent-flow: true
  protect-crops: true
  protect-inventories: true
  ?welcome-message: false
  ?farewell-message: false
  ?prevent-portal-enter: false
  ?prevent-portal-destination: false
  ?prevent-portal-create: false
  ?prevent-vehicle-enter: false
  ?prevent-vehicle-exit: false
  ?prevent-teleport: false
  command-blacklisting: false
  can-change-owner: true
  enable-on-src: true
  mixing-group: 1
  rentable: false
  buyable: false
  cuboid: false
- title: Cubo de ladrillo
  block: '97:2'
  radius: 10
  custom-height: 19
  meta-name: '&bCubo de ladrillo 10x10x10'
  meta-autoset: true
  meta-lore:
  - '&eprotege un area de 12x12x12'
  prevent-fire: true
  prevent-place: true
  prevent-destroy: true
  prevent-vehicle-destroy: true
  prevent-enderman-destroy: true
  prevent-explosions: true
  prevent-unprotectable: true
  prevent-item-frame-take: true
  protect-armor-stands: true
  prevent-flow: true
  protect-crops: true
  protect-inventories: true
  ?welcome-message: false
  ?farewell-message: false
  ?prevent-portal-enter: false
  ?prevent-portal-destination: false
  ?prevent-portal-create: false
  ?prevent-vehicle-enter: false
  ?prevent-vehicle-exit: false
  ?prevent-teleport: false
  command-blacklisting: false
  can-change-owner: true
  enable-on-src: true
  mixing-group: 1
  rentable: false
  buyable: false
  cuboid: false
- title: Cubo cincelado
  block: '97:5'
  radius: 12
  custom-height: 12
  meta-name: '&bCubo cincelado 12x12x12'
  meta-autoset: true
  meta-lore:
  - '&eprotege un area de 12x12x12'
  prevent-fire: true
  prevent-place: true
  prevent-destroy: true
  prevent-vehicle-destroy: true
  prevent-enderman-destroy: true
  prevent-explosions: true
  prevent-unprotectable: true
  prevent-item-frame-take: true
  protect-armor-stands: true
  prevent-flow: true
  protect-crops: true
  protect-inventories: true
  ?welcome-message: false
  ?farewell-message: false
  ?prevent-portal-enter: false
  ?prevent-portal-destination: false
  ?prevent-portal-create: false
  ?prevent-vehicle-enter: false
  ?prevent-vehicle-exit: false
  ?prevent-teleport: false
  command-blacklisting: false
  can-change-owner: true
  enable-on-src: true
  mixing-group: 1
  rentable: false
  buyable: false
  cuboid: false
bypass-blocks: []
unprotectable-blocks: []
```
