### ISSUE TITLE
Chests as fields is broken.

### ISSUE THREAD

**Issue by Psithief** [marcelo-mason/PreciousStones#298]
``` yaml
settings:
  show-debug-info: true
force-field-blocks:
- block: 54
```

Thanks to 'show-debug-info' I have found two things:
- When the block is placed, the bukkit event contains Block = 54 and Data = 3, no matter the orientation. That looks like a bug in Bukkit.
- `- block: 54` does not match 54:3, so I must put `- block: '54:3'`. The PS documentation suggests that the former should match every data. This means it's fortunate that the bukkit bug exists, because there's no way to make four blocks all act as the same type of field!

Alternatively, chest data is supposed to be interpreted differently?

Using v9.1.0 and Bukkit b2149
