### ISSUE TITLE
Phaed, I have a question regarding plots not overwriting parent field.

### ISSUE THREAD

**Issue by Esfekia** [marcelo-mason/PreciousStones#586]
Hi,

I am trying to make it so that the parent field (city protection), even for the allowed people, does not allow block place destroy, where people have to get a plot to be able to do that. This is what I have. However Even when a person is allowed on City Protect and has its plot, the plots prevent-place:true (which would still allow the owner and the allowed person to destroy/place) is not overwriting the City Protect's ^prevent-place:true (which prevents the allowed person to destroy/place)

Could you please tell me if I am doing something wrong?

```
- title: City Protection
  block: 57
  radius: 20
  custom-height: 15
  prevent-fire: true
  ^prevent-place: true
  ^prevent-place-blacklist:
  - 35
  ^prevent-destroy: true
  ^prevent-destroy-blacklist:
  - 35
  prevent-vehicle-destroy: true
  prevent-enderman-destroy: true
  prevent-explosions: true
  prevent-unprotectable: true
  prevent-item-frame-take: true
  prevent-flow: true
  protect-crops: true
  prevent-use:
  - 23
  - 54
  - 61
  - 62
  ?welcome-message: true
  ?farewell-message: true
  ?prevent-portal-enter: true
  ?prevent-portal-destination: true
  ?prevent-portal-create: true
  ?prevent-vehicle-enter: true
  ?prevent-vehicle-exit: true
  ?prevent-teleport: true
  command-blacklisting: true
  can-change-owner: true
  enable-on-src: true
  mixing-group: 1
  hidable: true
  cuboid: true
  mask-on-disabled: 80
- title: City Plot
  block: 35
  radius: 20
  custom-height: 15
  allowed-only-inside:
  - City Protection
  plot: true
  prevent-fire: true
  prevent-place: true
  prevent-destroy: true
  prevent-vehicle-destroy: true
  prevent-enderman-destroy: true
  prevent-explosions: true
  prevent-unprotectable: true
  prevent-flow: true
  ?prevent-teleport: true
  protect-crops: true
  ?welcome-message: true
  ?farewell-message: true
  can-change-owner: true
  enable-on-src: true
  mixing-group: 1
  hidable: true
  cuboid: true
  mask-on-disabled: 80
```
