### ISSUE TITLE
I have a Teleport problem within cityplot

### ISSUE THREAD

**Issue by MrKiller01** [marcelo-mason/PreciousStones#897]
As the title says, i looked at the config but the option Prevent telport is leaded by a question mark like this
```
- title: City Plot
  block: quartz_ore
  radius: 20
  custom-height: 15
  meta-name: '&bStads-deel'
  meta-autoset: true
  meta-lore:
  - '&eStads-deel beschermings gebied'
  - '&eHet beslaat een radiaal gebied van 20 radius'
  - '&eMet een maximale hoogte van 15'
  allowed-only-inside:
  - City Protection
  plot: true
  no-conflict: true
  prevent-use:
  - wooden_door
  - iron_door
  - spruce_door
  - birch_door
  - jungle_door
  - acacia_door
  - dark_oak_door
  prevent-fire: true
  prevent-place: true
  prevent-destroy: true
  prevent-vehicle-destroy: true
  prevent-enderman-destroy: true
  prevent-explosions: true
  prevent-unprotectable: true
  protect-inventories: false
  prevent-flow: true
  ?prevent-teleport: true
  protect-crops: true
  ?welcome-message: true
  ?farewell-message: true
  can-change-owner: true
  enable-on-src: true
  mixing-group: 1
  hidable: true
  rentable: true
  buyable: true
  cuboid: true
  mask-on-disabled: 80
```
I thought that it was off!!!! Or not?
