### ISSUE TITLE
Cannot open inventories for other plugins (protect-inventories)

### ISSUE THREAD

**Issue by kunpapa** [marcelo-mason/PreciousStones#985]
On a field with that flag (doesnt mather if it is enable or disable, just setted) players wont be able to use menu of another plugins because the flag deny it.

**Comment by marcelo-mason** [comment]
Can you post your config for that field?

**Comment by kunpapa** [comment]
```
force-field-blocks:
- title: Coal Protection
  block: 16
  radius: 5
  prevent-fire: true
  prevent-place: true
  prevent-use:
  - 58
  plot: true
  prevent-destroy: true
  prevent-vehicle-destroy: true
  prevent-enderman-destroy: true
  prevent-explosions: true
  prevent-item-frame-take: true
  prevent-potion-splash: true
  ?prevent-mob-spawn: false
  ?prevent-animal-spawn: false
  prevent-flow: true
  prevent-lwc: true
  ?prevent-villagers: true
  protect-crops: true
  protect-inventories: true
  ?protect-villagers: true
  ?prevent-teleport: false
  ?protect-animals: false
  ?welcome-message: true
  ?farewell-message: true
  ?prevent-portal-enter: true
  ?prevent-portal-destination: true
  ?prevent-portal-create: true
  ?prevent-vehicle-enter: true
  ?prevent-vehicle-exit: true
  ?entry-alert: false
  ?dynmap-area: true
  no-projectile-throw: true
  mixing-group: 0
  hidable: true
  cuboid: false
  allowed-can-break: false
  visualize-on-place: true
  sneak-to-place: true
  translocation-safety: true
  worldguard-repellent: true
  single-use: true
  shareable: true
  buyable: true
  allowed-only-outside:
  - Protection City1
  - Protection City2
  - Plot1
  - Plot2
  limits:
  - 3
  - 10
  - 30
  - 40
  - 50
```
